// <auto-generated />
using IoTMonitoringSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace IoTMonitoringSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260621000000_AddAgentActionProposals")]
    partial class AddAgentActionProposals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Model state at this migration is captured in ApplicationDbContextModelSnapshot.
#pragma warning restore 612, 618
        }
    }
}
